import * as Dialog from '@radix-ui/react-dialog';
import { useState, type FormEvent } from 'react';
import { Button } from './ui/button';
export default function Connect({kind='contact'}:{kind?:string}) {
const [service,setService]=useState(kind==='speaking'?'Public speaking':kind==='yoga'?'Yoga':'Development');
const [name,setName]=useState('');const [email,setEmail]=useState('');const [details,setDetails]=useState('');const [budget,setBudget]=useState('');const [currency,setCurrency]=useState('USD');const [timezone,setTimezone]=useState('');
const label=kind==='development'?'Hire for development':kind==='speaking'?'Book public speaking':kind==='yoga'?'Yoga inquiry':'Book a conversation';
function compose(e:FormEvent<HTMLFormElement>){e.preventDefault();const body=`Name: ${name.trim()}\nEmail: ${email.trim()}\nInquiry: ${service}\nBudget: ${budget.trim()} ${currency}\nTimezone / location: ${timezone.trim()}\n\n${details.trim()}`;window.location.href=`mailto:mail@jahnoah.com?subject=${encodeURIComponent(service+' inquiry')}&body=${encodeURIComponent(body)}`;}
return <Dialog.Root><Dialog.Trigger asChild><Button>{label}</Button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog-content"><Dialog.Title className="dialog-title">Book a conversation</Dialog.Title><Dialog.Description className="dialog-description">mail@jahnoah.com</Dialog.Description><form className="inquiry-form" onSubmit={compose}><label htmlFor={`service-${kind}`}>Inquiry<select id={`service-${kind}`} value={service} onChange={e=>setService(e.target.value)}><option>Development</option><option>Public speaking</option><option>Yoga</option><option>Other</option></select></label><div className="form-pair"><label htmlFor={`name-${kind}`}>Name<input id={`name-${kind}`} autoComplete="name" value={name} onChange={e=>setName(e.target.value)} required maxLength={120}/></label><label htmlFor={`email-${kind}`}>Email<input id={`email-${kind}`} type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required maxLength={200}/></label></div><div className="form-pair"><label htmlFor={`budget-${kind}`}>Budget (optional)<input id={`budget-${kind}`} value={budget} onChange={e=>setBudget(e.target.value)} maxLength={60}/></label><label htmlFor={`currency-${kind}`}>Currency<select id={`currency-${kind}`} value={currency} onChange={e=>setCurrency(e.target.value)}><option>USD</option><option>EUR</option><option>GBP</option><option>CAD</option><option>AUD</option><option>Other</option></select></label></div><label htmlFor={`timezone-${kind}`}>Timezone / location (optional)<input id={`timezone-${kind}`} value={timezone} onChange={e=>setTimezone(e.target.value)} maxLength={120}/></label><label htmlFor={`details-${kind}`}>Project or event details<textarea id={`details-${kind}`} value={details} onChange={e=>setDetails(e.target.value)} rows={4} maxLength={3000} required placeholder="Scope, location, preferred dates"/></label><Button type="submit">Open email draft</Button><a className="text-link" href="mailto:mail@jahnoah.com">Email directly</a></form><Dialog.Close asChild><Button variant="outline">Close</Button></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
